### PR TITLE
Add french translation in fr.ts file

### PR DESCRIPTION
**Pull request by romainbh**

### CODE REVIEW

**Comment by piMoll** [comment]
Thanks so much for the french translations!

**Comment by romainbh** [comment]
> Thanks so much for the french translations!

You're welcome! Thanks for this useful plugin! I will use it for GIS teaching in Bildungszentrumwald Lyss with the french class ;-)

**Comment by piMoll** [comment]
Awesome that you use it in class! 
I'm planning the next release for late December. Would that be ok for you? Or do you need the translations earlier?

**Comment by romainbh** [comment]
Thank you for asking, late December is all OK! The new class will start in January, and the raster teaching part will come later.

**Pull request merged**
